
# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    name: Run tests
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        working-directory: ./docs
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
        working-directory: ./docs
        #👇 Adds Chromatic as a step in the workflow
      - name: Use Chroma UI
        uses: chromaui/action@v1
        working-directory: ./docs
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}