# Based on https://betterprogramming.pub/unleashing-github-workflow-environments-40e550fde009

# name: Build and Publish storybook to GitHub Pages
name: Deploy

on:
  push:
    branches: [ main, test ]

jobs:

  deploy-testing:
    name: Deploy to testing
    environment:
      name: Testing
    if: github.event.ref == 'refs/heads/test'  
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to testing using ${{ secrets.mysecret }}
        working-directory: ../docs

  deploy-staging:
    name: Deploy to staging
    environment:
      name: Staging
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging using ${{ secrets.mysecret }}
        working-directory: ../docs

  deploy-production:
    name: Deploy to production
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write    
    environment:
      name: Production
      url: ${{ steps.build-publish.outputs.page_url }}
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production using {{ secrets.mysecret }}
        working-directory: ../docs
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: storybook-static
          build_command: NODE_ENV=production npm run build && npm run build:storybook
