# Based on https://betterprogramming.pub/unleashing-github-workflow-environments-40e550fde009

# name: Build and Publish storybook to GitHub Pages
name: Deploy

on:
  push:
    branches: [ main ]
#      - "master"
#  workflow_dispatch:
jobs:

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging using ${{ secrets.mysecret-stag }}

  deploy-production:
    name: Deploy to production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production using {{ secrets.mysecret-prod }}
    
#  deploy:
#    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
#    permissions:
#      contents: read
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.build-publish.outputs.page_url }}
#    runs-on: ubuntu-latest
#    steps:
#    - id: build-publish
#      uses: bitovi/github-actions-react-to-ghp@v1.2.0
#      with:
#        path: storybook-static
#        build_command: NODE_ENV=production npm run build && npm run build:storybook
